apiVersion: v1
kind: Service
metadata:
  name: k8s-deployment-scale
  labels:
    provider: k8s-deployment-scale
    heritage: helm
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8000
  selector:
    provider: k8s-deployment-scale